[package]
name = "term_planner"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
libc = "0.2.172"
rustyline = "15.0.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
