name: CI, Tag & Release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  actions: write

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine bump level
        id: bump
        run: |
          LEVEL="patch"
          BRANCH="${GITHUB_REF##*/}"
          if [[ "$BRANCH" =~ ^feature/ ]]; then
            LEVEL="minor"
          elif [[ "$BRANCH" =~ ^fix/ ]]; then
            LEVEL="patch"
          elif [[ "$BRANCH" =~ ^release/ ]]; then
            LEVEL="major"
          fi
          echo "level=$LEVEL" >> $GITHUB_OUTPUT

      - name: Bump Cargo.toml version
        id: bumpver
        run: |
          set +e
          OLD=$(grep '^version =' Cargo.toml | cut -d\" -f2) || OLD="0.0.0"
          IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD" || true

          case "${{ steps.bump.outputs.level }}" in
            major) ((MAJOR++)); MINOR=0; PATCH=0 ;;
            minor) ((MINOR++)); PATCH=0 ;;
            *)     ((PATCH++)) ;;
          esac
          NEW="$MAJOR.$MINOR.$PATCH"

          echo "old=$OLD" >> $GITHUB_OUTPUT
          echo "new=$NEW" >> $GITHUB_OUTPUT

          if [[ "$NEW" != "$OLD" ]]; then
            sed -i.bak -E "/^\[package\]$/,/^\[/ s/^version = \"$OLD\"/version = \"$NEW\"/" Cargo.toml \
              || echo "sed failed, but continuing"
          fi
          set -e

      - name: Update Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: update

      - name: Commit bump and push tag
        if: steps.bumpver.outputs.new != steps.bumpver.outputs.old
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml Cargo.lock
          git commit -m "chore: bump version ${{ steps.bumpver.outputs.new }}"
          git tag -a "v${{ steps.bumpver.outputs.new }}" -m "Release v${{ steps.bumpver.outputs.new }}"
          git push origin main --follow-tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.bumpver.outputs.new }}
          name: Release v${{ steps.bumpver.outputs.new }}
          token: ${{ secrets.GITHUB_TOKEN }}
